apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-service
  namespace: lab-01
spec:
  selector:
    app: hello-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
